#!/bin/bash
mkdir -p ~/.jupyter
cat > ~/.jupyter/jupyter_server_config.json << 'EOF'
{
  "ServerApp": {
    "jpserver_extensions": {
      "voila": true
    }
  }
}
EOF

cat > ~/.jupyter/voila.json << 'EOF'
{
  "TagRemovePreprocessor": {
    "enabled": true,
    "remove_cell_tags": ["hide"]
  }
}
EOF
